version = 0.1
[default]
[default.global.parameters]
stack_name = "CfMacro-Boto3"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
confirm_changeset = false
resolve_s3 = true
capabilities = "CAPABILITY_IAM"

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"


[test]
[test.global.parameters]
stack_name = "CfMacro-Boto3-test"
confirm_changeset = false
resolve_s3 = true
capabilities = "CAPABILITY_IAM"
template = "test.yaml"
