AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: python3.13
    CodeUri: lambda
    Architectures:
      - arm64

Resources:
  MacroFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: macro.handler
  
  Macro:
    Type: AWS::CloudFormation::Macro
    Properties:
      Name: 'String'
      Description: Provides various string processing functions
      FunctionName: !GetAtt MacroFunction.Arn
